### ISSUE TITLE
check if we can show plantuml files within github page

### ISSUE THREAD

**Issue by fernandoocampo** [akatsuki-members/credit-crypto#18]
https://gist.github.com/noamtamim/f11982b28602bd7e604c233fbe9d910f

**Comment by wilorios** [comment]
Yep, it is possible, besides there are alternatives to use the online plantuml server also, i.e:
https://github.com/marketplace/actions/generate-plantuml

**Comment by wilorios** [comment]
Yep, this is possible, there are another way ussing this 

https://github.com/marketplace/actions/generate-plantuml
