### ISSUE TITLE
define service security. JWT or other.

### ISSUE THREAD

**Issue by fernandoocampo** [akatsuki-members/credit-crypto#9]
https://github.com/akatsuki-members/credit-crypto/wiki/Architecture-Decision-Record#security-token-based-authentication

**Comment by wilorios** [comment]
Reviewing PASETO
https://github.com/o1egl/paseto

**Comment by wilorios** [comment]
Ok, it was docummented in https://github.com/akatsuki-members/credit-crypto/wiki/Architecture-Decision-Record#security-token-based-authentication
